version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user@123
    ports:
      - "3306:3306"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_container
    restart: always
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  
